export const coursesData = {

    "mern-stack": {
      title: "MERN Stack",
      heroTitle: "Become a",
      heroTitleBold: "MERN Stack",
      heroTitleEnd: "Developer",
      heroBadge: "New Batch — 2025",
      heroSub: "Master the most powerful JavaScript full-stack combination — MongoDB, Express, React and Node. Build real-world production apps, work in a real office environment, and land your developer job with Royalfinity's premium mentorship.",
      stackBadges: [
        { label: "MongoDB",    cls: "stack-php"     },
        { label: "Express.js", cls: "stack-laravel"  },
        { label: "React.js",   cls: "stack-mysql"    },
        { label: "Node.js",    cls: "stack-html"     },
        { label: "REST APIs",  cls: "stack-js"       },
      ],
      stats: [
        { num: "400+", label: "Students Placed"    },
        { num: "6",    label: "Months Program"     },
        { num: "10+",  label: "Live Projects"      },
        { num: "4.8★", label: "Avg. Rating"        },
        { num: "₹0",   label: "Premium Tools Cost" },
      ],
      price: "₹15,999",
      originalPrice: "₹30,000",
      overviewTitle: "Everything you need to",
      overviewTitleEm: "build & deploy",
      overviewDesc: "MERN Stack is the most in-demand full-stack skill set in the modern web industry. This course takes you from JavaScript fundamentals to deploying full-stack React + Node applications — with 4 months of deep structured learning followed by 2 months of intense real-world project work, giving you a portfolio that actually gets you hired.",
      highlights: [
        { icon: "🗓️", title: "Duration & Schedule",  desc: "6 months | 5 days/week | Weekday batches available" },
        { icon: "🏢", title: "Office Environment",    desc: "Learn in a real office setup — desks, dual monitors, team collaboration" },
        { icon: "🧑‍💻", title: "Mode of Learning",     desc: "Hybrid — Live classes + recorded sessions available 24/7" },
        { icon: "🏆", title: "Certification",         desc: "Industry-recognized certificate upon completion + LinkedIn endorsement" },
        { icon: "💼", title: "Placement Assistance",  desc: "Resume building, mock interviews & direct referrals to hiring partners" },
        { icon: "⚡", title: "Prerequisites",         desc: "Basic computer knowledge — no prior coding experience needed" },
      ],
      cardFeatures: [
        "Full 6-month structured curriculum",
        "Premium tools provided for free (worth ₹12k+)",
        "Real office environment access",
        "1-on-1 doubt sessions with mentors",
        "10+ real-world projects to build",
        "2 months dedicated hands-on project work",
        "Placement support & mock interviews",
        "Lifetime access to recorded classes",
        "Industry-recognized certificate",
        "Dedicated WhatsApp support group",
      ],
      curriculumTitle: "6 Months,",
      curriculumTitleEm: "Zero Gaps",
      curriculumDesc: "4 months of structured syllabus covering every core MERN concept — followed by 2 months of pure hands-on project work where you build, ship and present real applications just like a professional dev team.",
      modules: [
        { num: "01", phase: "Phase 1 · Month 1", title: "Web Foundations + JavaScript", practical: false, topics: ["HTML5 semantics & CSS3 layouts","Flexbox, Grid & Responsive Design","JavaScript fundamentals — ES6+ syntax","DOM manipulation & event handling","Async JS — Promises, async/await, Fetch API","Git & GitHub version control"] },
        { num: "02", phase: "Phase 2 · Month 2", title: "React.js — Frontend Mastery",  practical: false, topics: ["React setup, JSX & component architecture","Props, State & lifecycle methods","React Hooks — useState, useEffect, useContext","React Router for SPA navigation","Redux Toolkit for state management","Tailwind CSS with React components"] },
        { num: "03", phase: "Phase 3 · Month 3", title: "Node.js + Express.js Backend",  practical: false, topics: ["Node.js runtime & npm ecosystem","Express.js server setup & routing","REST API design & best practices","Middleware — auth, error handling, CORS","JWT authentication & bcrypt security","File uploads with Multer & Cloudinary"] },
        { num: "04", phase: "Phase 4 · Month 4", title: "MongoDB + Full Stack Integration", practical: false, topics: ["MongoDB Atlas setup & NoSQL concepts","Mongoose ODM — schemas, models & queries","CRUD operations with React + Node + MongoDB","Full-stack app architecture & deployment","Socket.io for real-time features","Deployment on Render / Railway / Vercel"] },
        { num: "05", phase: "Phase 5 · Month 5 & 6", title: "Real-World Projects + Career Prep", practical: true, topics: ["Build a full-stack e-commerce app (React + Node + MongoDB)","Real-time chat application using Socket.io","Job board portal with admin dashboard","Team-based agile workflow — sprints & code reviews","GitHub portfolio optimization & project documentation","Mock interviews, resume building & placement drive"] },
      ],
      tools: [
        { emoji: "💡", name: "VS Code + Extensions Pack", desc: "The #1 code editor with premium dev extensions" },
        { emoji: "🗄️", name: "MongoDB Compass",           desc: "Visual GUI client for MongoDB databases" },
        { emoji: "🐙", name: "GitHub Pro",                desc: "Unlimited private repos + Copilot access" },
        { emoji: "📮", name: "Postman API",               desc: "Professional API testing & documentation" },
        { emoji: "🎨", name: "Figma Professional",        desc: "Design your app UI before you code it" },
        { emoji: "☁️", name: "Cloudinary",                desc: "Media storage & image management for MERN apps" },
        { emoji: "📝", name: "Notion Teams",              desc: "Project planning & sprint documentation" },
        { emoji: "🚀", name: "Render / Vercel Pro",       desc: "Deploy full-stack MERN apps on cloud for free" },
      ],
      ctaTitle: "Your career as a MERN Stack Developer",
      ctaTitleEm: "starts right now",
      ctaDesc: "Join 400+ students who transformed their lives with Royalfinity's MERN Stack program. New batch starting soon — seats fill fast.",
    },
  
    // ─────────────────────────────────────────────
    "php-stack": {
      title: "PHP Full Stack",
      heroTitle: "Become a",
      heroTitleBold: "PHP Full Stack",
      heroTitleEnd: "Developer",
      heroBadge: "New Batch — 2025",
      heroSub: "Master PHP, MySQL, and Laravel — the backbone of millions of websites. Learn to build complete web applications from scratch with Royalfinity's structured mentorship.",
      stackBadges: [
        { label: "PHP",        cls: "stack-php"     },
        { label: "MySQL",      cls: "stack-mysql"   },
        { label: "Laravel",    cls: "stack-laravel" },
        { label: "HTML/CSS",   cls: "stack-html"    },
        { label: "JavaScript", cls: "stack-js"      },
      ],
      stats: [
        { num: "300+", label: "Students Placed"    },
        { num: "6",    label: "Months Program"     },
        { num: "8+",   label: "Live Projects"      },
        { num: "4.7★", label: "Avg. Rating"        },
        { num: "₹0",   label: "Premium Tools Cost" },
      ],
      price: "₹14,999",
      originalPrice: "₹28,000",
      overviewTitle: "Everything you need to",
      overviewTitleEm: "build & launch",
      overviewDesc: "PHP powers over 75% of the web. This course takes you from HTML basics to building full-featured Laravel applications — with hands-on projects, real office environment, and placement support to get you job-ready.",
      highlights: [
        { icon: "🗓️", title: "Duration & Schedule",  desc: "6 months | 5 days/week | Weekday batches available" },
        { icon: "🏢", title: "Office Environment",    desc: "Learn in a real office setup — desks, dual monitors, team collaboration" },
        { icon: "🧑‍💻", title: "Mode of Learning",     desc: "Hybrid — Live classes + recorded sessions available 24/7" },
        { icon: "🏆", title: "Certification",         desc: "Industry-recognized certificate upon completion + LinkedIn endorsement" },
        { icon: "💼", title: "Placement Assistance",  desc: "Resume building, mock interviews & direct referrals to hiring partners" },
        { icon: "⚡", title: "Prerequisites",         desc: "Basic computer knowledge — no prior coding experience needed" },
      ],
      cardFeatures: [
        "Full 6-month structured curriculum",
        "Premium tools provided for free (worth ₹10k+)",
        "Real office environment access",
        "1-on-1 doubt sessions with mentors",
        "8+ real-world projects to build",
        "2 months dedicated hands-on project work",
        "Placement support & mock interviews",
        "Lifetime access to recorded classes",
        "Industry-recognized certificate",
        "Dedicated WhatsApp support group",
      ],
      curriculumTitle: "6 Months,",
      curriculumTitleEm: "Zero Gaps",
      curriculumDesc: "4 months of structured PHP & Laravel syllabus followed by 2 months of real project work — building complete web apps just like a professional dev team.",
      modules: [
        { num: "01", phase: "Phase 1 · Month 1", title: "Web Foundations + HTML/CSS", practical: false, topics: ["HTML5 semantics & page structure","CSS3 — Flexbox, Grid & Responsive Design","Bootstrap 5 for rapid UI development","JavaScript fundamentals & DOM manipulation","Git & GitHub version control","VS Code setup & dev environment"] },
        { num: "02", phase: "Phase 2 · Month 2", title: "PHP Core + MySQL Database",  practical: false, topics: ["PHP syntax, variables & control flow","Functions, arrays & form handling","MySQL database design & queries","PHP + MySQL CRUD operations","Sessions, cookies & authentication","File handling & error management"] },
        { num: "03", phase: "Phase 3 · Month 3", title: "Laravel Framework",          practical: false, topics: ["Laravel installation & MVC architecture","Routing, controllers & blade templates","Eloquent ORM & database migrations","Laravel Auth — login, register, roles","REST API development with Laravel","Middleware, validation & error handling"] },
        { num: "04", phase: "Phase 4 · Month 4", title: "Advanced Laravel + Integrations", practical: false, topics: ["Payment gateway integration (Razorpay)","Email & notification systems","File uploads & media management","Laravel queues & scheduled tasks","API consumption with Axios & Fetch","Deployment on cPanel & VPS servers"] },
        { num: "05", phase: "Phase 5 · Month 5 & 6", title: "Real-World Projects + Career Prep", practical: true, topics: ["E-commerce website with admin panel","School management system","Job portal with employer & student roles","Team sprints & agile workflow","GitHub portfolio & project documentation","Mock interviews, resume building & placement"] },
      ],
      tools: [
        { emoji: "💡", name: "VS Code + Extensions Pack", desc: "The #1 code editor with PHP & Laravel extensions" },
        { emoji: "🐬", name: "MySQL Workbench",           desc: "Visual database design & management tool" },
        { emoji: "🐙", name: "GitHub Pro",                desc: "Unlimited private repos + Copilot access" },
        { emoji: "📮", name: "Postman API",               desc: "Professional API testing & documentation" },
        { emoji: "🎨", name: "Figma Professional",        desc: "Design your app UI before you code it" },
        { emoji: "🖥️", name: "XAMPP / Laragon",           desc: "Local PHP development environment" },
        { emoji: "📝", name: "Notion Teams",              desc: "Project planning & sprint documentation" },
        { emoji: "🚀", name: "cPanel + Hostinger",        desc: "Deploy PHP Laravel apps on live hosting" },
      ],
      ctaTitle: "Your career as a PHP Full Stack Developer",
      ctaTitleEm: "starts right now",
      ctaDesc: "Join 300+ students who transformed their lives with Royalfinity's PHP Full Stack program. New batch starting soon — seats fill fast.",
    },
  
    // ─────────────────────────────────────────────
    "digital-marketing": {
      title: "Digital Marketing",
      heroTitle: "Master",
      heroTitleBold: "Digital Marketing",
      heroTitleEnd: "& Grow Brands",
      heroBadge: "New Batch — 2025",
      heroSub: "Learn SEO, social media marketing, Google Ads, content strategy and more. Become a certified digital marketer and land high-paying roles or grow your own business with Royalfinity's practical training.",
      stackBadges: [
        { label: "SEO",          cls: "stack-php"     },
        { label: "Google Ads",   cls: "stack-mysql"   },
        { label: "Meta Ads",     cls: "stack-laravel" },
        { label: "Canva Pro",    cls: "stack-html"    },
        { label: "Analytics",    cls: "stack-js"      },
      ],
      stats: [
        { num: "250+", label: "Students Placed"    },
        { num: "4",    label: "Months Program"     },
        { num: "5+",   label: "Live Campaigns"     },
        { num: "4.8★", label: "Avg. Rating"        },
        { num: "₹0",   label: "Premium Tools Cost" },
      ],
      price: "₹12,999",
      originalPrice: "₹24,000",
      overviewTitle: "Everything you need to",
      overviewTitleEm: "market & grow",
      overviewDesc: "Digital Marketing is the fastest growing career field in India. This course covers every channel — SEO, paid ads, social media, email & analytics — with live campaign work so you graduate with real results to show.",
      highlights: [
        { icon: "🗓️", title: "Duration & Schedule",  desc: "4 months | 5 days/week | Weekday batches available" },
        { icon: "🏢", title: "Office Environment",    desc: "Learn in a real office setup — desks, dual monitors, team collaboration" },
        { icon: "🧑‍💻", title: "Mode of Learning",     desc: "Hybrid — Live classes + recorded sessions available 24/7" },
        { icon: "🏆", title: "Certification",         desc: "Google & Meta certified + Royalfinity certificate upon completion" },
        { icon: "💼", title: "Placement Assistance",  desc: "Resume building, mock interviews & direct referrals to hiring partners" },
        { icon: "⚡", title: "Prerequisites",         desc: "Basic computer knowledge — no prior marketing experience needed" },
      ],
      cardFeatures: [
        "Full 4-month structured curriculum",
        "Premium tools provided for free (worth ₹8k+)",
        "Real office environment access",
        "Live campaign execution with real budgets",
        "Google Ads & Meta Ads certifications",
        "1-on-1 doubt sessions with mentors",
        "Placement support & mock interviews",
        "Lifetime access to recorded classes",
        "Industry-recognized certificate",
        "Dedicated WhatsApp support group",
      ],
      curriculumTitle: "4 Months,",
      curriculumTitleEm: "All Channels",
      curriculumDesc: "A structured month-by-month journey covering every digital marketing channel — from SEO and content to paid ads and analytics — with live campaign work throughout.",
      modules: [
        { num: "01", phase: "Phase 1 · Month 1", title: "SEO + Content Marketing", practical: false, topics: ["On-page & off-page SEO fundamentals","Keyword research with Ahrefs & SEMrush","Technical SEO — site speed, schema, crawling","Content strategy & blog writing for SEO","Link building techniques","Google Search Console & Analytics setup"] },
        { num: "02", phase: "Phase 2 · Month 2", title: "Social Media Marketing",  practical: false, topics: ["Instagram, Facebook & LinkedIn strategy","Content calendar creation & scheduling","Canva Pro for social media design","Reels, Shorts & video content strategy","Community management & engagement","Influencer & UGC marketing basics"] },
        { num: "03", phase: "Phase 3 · Month 3", title: "Paid Advertising — Google & Meta", practical: false, topics: ["Google Search, Display & YouTube Ads","Meta Ads Manager — Facebook & Instagram","Audience targeting & retargeting","Ad copywriting & creative best practices","Budget management & bid strategies","Conversion tracking & pixel setup"] },
        { num: "04", phase: "Phase 4 · Month 4", title: "Analytics + Live Campaigns", practical: true, topics: ["Google Analytics 4 deep dive","Data Studio dashboards & reporting","Email marketing with Mailchimp","Live campaign — manage real ad budgets","Complete brand digital audit project","Resume building, certifications & placement drive"] },
      ],
      tools: [
        { emoji: "🔍", name: "SEMrush / Ahrefs",          desc: "Professional SEO & competitor research tools" },
        { emoji: "🎨", name: "Canva Pro",                  desc: "Design stunning social media creatives" },
        { emoji: "📊", name: "Google Analytics 4",         desc: "Track and analyze website performance" },
        { emoji: "📢", name: "Meta Ads Manager",           desc: "Run Facebook & Instagram ad campaigns" },
        { emoji: "📧", name: "Mailchimp",                  desc: "Email marketing & automation platform" },
        { emoji: "🎬", name: "CapCut Pro",                 desc: "Video editing for Reels & Shorts" },
        { emoji: "📝", name: "Notion Teams",               desc: "Content calendar & campaign planning" },
        { emoji: "📈", name: "Google Data Studio",         desc: "Build beautiful marketing dashboards" },
      ],
      ctaTitle: "Your career as a Digital Marketer",
      ctaTitleEm: "starts right now",
      ctaDesc: "Join 250+ students who transformed their careers with Royalfinity's Digital Marketing program. New batch starting soon — seats fill fast.",
    },
  
    // ─────────────────────────────────────────────
    "performance-marketing": {
      title: "Performance Marketing",
      heroTitle: "Master",
      heroTitleBold: "Performance Marketing",
      heroTitleEnd: "& Drive ROI",
      heroBadge: "New Batch — 2025",
      heroSub: "Specialise in data-driven paid media — Meta Ads, Google Ads, conversion rate optimisation and ROI analysis. Become the marketer brands pay top rupees to hire.",
      stackBadges: [
        { label: "Meta Ads",    cls: "stack-laravel" },
        { label: "Google Ads",  cls: "stack-mysql"   },
        { label: "A/B Testing", cls: "stack-php"     },
        { label: "CRO",         cls: "stack-html"    },
        { label: "Analytics",   cls: "stack-js"      },
      ],
      stats: [
        { num: "150+", label: "Students Placed"    },
        { num: "3",    label: "Months Program"     },
        { num: "4+",   label: "Live Campaigns"     },
        { num: "4.9★", label: "Avg. Rating"        },
        { num: "₹0",   label: "Premium Tools Cost" },
      ],
      price: "₹11,999",
      originalPrice: "₹22,000",
      overviewTitle: "Everything you need to",
      overviewTitleEm: "scale & convert",
      overviewDesc: "Performance Marketing is the highest-paying niche in digital marketing. This course focuses on data, paid campaigns, testing and ROI — giving you the skills that e-commerce brands, startups and agencies are desperately hiring for.",
      highlights: [
        { icon: "🗓️", title: "Duration & Schedule",  desc: "3 months | 5 days/week | Weekday batches available" },
        { icon: "🏢", title: "Office Environment",    desc: "Learn in a real office setup — desks, dual monitors, team collaboration" },
        { icon: "🧑‍💻", title: "Mode of Learning",     desc: "Hybrid — Live classes + recorded sessions available 24/7" },
        { icon: "🏆", title: "Certification",         desc: "Google & Meta certified + Royalfinity certificate upon completion" },
        { icon: "💼", title: "Placement Assistance",  desc: "Resume building, mock interviews & direct referrals to hiring partners" },
        { icon: "⚡", title: "Prerequisites",         desc: "Basic digital marketing knowledge preferred but not required" },
      ],
      cardFeatures: [
        "Full 3-month intensive curriculum",
        "Premium tools provided for free (worth ₹6k+)",
        "Real office environment access",
        "Live campaign execution with real budgets",
        "Google & Meta certification prep",
        "1-on-1 doubt sessions with mentors",
        "Placement support & mock interviews",
        "Lifetime access to recorded classes",
        "Industry-recognized certificate",
        "Dedicated WhatsApp support group",
      ],
      curriculumTitle: "3 Months,",
      curriculumTitleEm: "Pure Performance",
      curriculumDesc: "An intensive, data-first curriculum covering paid media strategy, campaign execution, A/B testing and ROI reporting — the exact skills performance marketing agencies hire for.",
      modules: [
        { num: "01", phase: "Phase 1 · Month 1", title: "Paid Ads Foundations", practical: false, topics: ["Meta Ads Manager — full setup & structure","Google Search & Display Ads mastery","Audience research & targeting strategy","Ad creative — copy, visuals & video","Campaign structure — campaigns, ad sets, ads","Pixel & conversion tracking setup"] },
        { num: "02", phase: "Phase 2 · Month 2", title: "Advanced Campaigns & CRO", practical: false, topics: ["Retargeting & lookalike audience strategy","Landing page optimisation (CRO)","A/B testing — ads, creatives & landing pages","Funnel building — TOFU, MOFU, BOFU","E-commerce campaigns — catalogue & dynamic ads","Budget scaling & bid strategy optimisation"] },
        { num: "03", phase: "Phase 3 · Month 3", title: "Analytics, Reporting & Live Campaigns", practical: true, topics: ["GA4 advanced — events, funnels & attribution","Google Data Studio reporting dashboards","Live campaign — manage real client budgets","ROAS analysis & performance reporting","Portfolio: 2 complete campaign case studies","Mock interviews, resume building & placement drive"] },
      ],
      tools: [
        { emoji: "📢", name: "Meta Ads Manager",    desc: "Run & optimise Facebook & Instagram campaigns" },
        { emoji: "🔎", name: "Google Ads",          desc: "Search, Display, Shopping & YouTube campaigns" },
        { emoji: "📊", name: "Google Analytics 4",  desc: "Advanced tracking & attribution analysis" },
        { emoji: "🧪", name: "VWO / Google Optimize",desc: "A/B testing & conversion optimisation" },
        { emoji: "📈", name: "Google Data Studio",  desc: "Client-ready performance dashboards" },
        { emoji: "🎨", name: "Canva Pro",           desc: "Create high-converting ad creatives" },
        { emoji: "📝", name: "Notion Teams",        desc: "Campaign planning & reporting docs" },
        { emoji: "🔍", name: "SEMrush",             desc: "Competitor & keyword research for paid ads" },
      ],
      ctaTitle: "Your career as a Performance Marketer",
      ctaTitleEm: "starts right now",
      ctaDesc: "Join 150+ students who mastered paid media with Royalfinity's Performance Marketing program. New batch starting soon — seats fill fast.",
    },
  
  }